.\" Manpage for opendlv-proxy-cfsd18-proxy-sick
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-proxy-cfsd18-proxy-sick 1 "26 September 2017" "0.11.0" "opendlv-proxy-cfsd18-proxy-sick man page"

.SH NAME
opendlv-proxy-cfsd18-proxy-sick \- This tool interfaces with the Sick lidar device.



.SH SYNOPSIS
.B opendlv-proxy-cfsd18-proxy-sick --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-cfsd18-proxy-sick --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

